export type Entry = { en: string; ro: string };

export const dict: Record<string, Entry> = {
  "nav.facility": { en: "Facility", ro: "Facilități" },
  "nav.services": { en: "Services", ro: "Servicii" },
  "nav.offices": { en: "Offices", ro: "Birouri" },
  "nav.contact": { en: "Contact", ro: "Contact" },
  "nav.quote": { en: "Get a quote", ro: "Cere ofertă" },
  "hero.title": {
    en: 'ITC Logistic — your forwarding partner for <em style="font-style:normal;color:#007A3D">transport&nbsp;&amp;&nbsp;logistics</em>.',
    ro: 'ITC Logistic — partenerul tău de expediție pentru <em style="font-style:normal;color:#007A3D">transport&nbsp;&amp;&nbsp;logistică</em>.',
  },
  "hero.lead": {
    en: "Contract warehousing in Brasov &amp; Timisoara, road transport and air &amp; ocean freight — with offices in 5 Romanian cities, serving clients across Europe.",
    ro: "Depozitare contractuală la Brașov și Timișoara, transport rutier și expediții aeriene &amp; maritime — cu birouri în 5 orașe din România, pentru clienți din toată Europa.",
  },
  "hero.cta1": { en: "Talk to our team", ro: "Vorbește cu echipa" },
  "hero.cta2": { en: "Our services", ro: "Serviciile noastre" },
  "hero.scroll": { en: "Scroll", ro: "Derulează" },
  "chips.iata": { en: "IATA cargo agent", ro: "Agent cargo IATA" },
  "chips.wh": { en: "28,500 m² warehousing", ro: "28.500 m² depozitare" },
  "stagecap.port.eyebrow": { en: "Port &amp; air cargo", ro: "Port &amp; cargo aerian" },
  "stagecap.port.title": {
    en: "Every border, every mode, one point of contact.",
    ro: "Fiecare graniță, fiecare mod de transport, un singur contact.",
  },
  "stagecap.port.text": {
    en: "IATA-certified air freight and ocean forwarding — customs handled end to end.",
    ro: "Expediții aeriene certificate IATA și transport maritim — cu vamă gestionată integral.",
  },
  "stagecap.city.eyebrow": { en: "Road transport", ro: "Transport rutier" },
  "stagecap.city.title": { en: "On the road, across Europe.", ro: "Pe drum, în toată Europa." },
  "stagecap.city.text": {
    en: "FTL, LTL and milk-run schedules — our own fleet reaches wherever your cargo needs to go.",
    ro: "FTL, LTL și rute milk-run — flota noastră ajunge oriunde ai nevoie de marfă.",
  },
  "mission.eyebrow": { en: "Who we are", ro: "Cine suntem" },
  "mission.title": {
    en: '<strong style="color:#14201A;font-weight:600">Your cargo.</strong><br>Our mission.<br>Welcome to <span style="color:#007A3D;font-weight:600">ITC</span>.',
    ro: '<strong style="color:#14201A;font-weight:600">Marfa ta.</strong><br>Misiunea noastră.<br>Bine ai venit la <span style="color:#007A3D;font-weight:600">ITC</span>.',
  },
  "mission.lead": {
    en: "From our own warehouses in Brasov and Timisoara we receive, store and prepare goods for clients across manufacturing, retail and distribution — so your operations never wait. What we commit to, we deliver.",
    ro: "Din depozitele noastre din Brașov și Timișoara recepționăm, stocăm și pregătim marfa pentru clienți din producție, retail și distribuție — astfel încât operațiunile tale să nu aștepte niciodată. Ce promitem, livrăm.",
  },
  "mission.cta1": { en: "What we do", ro: "Ce facem" },
  "stats.1": { en: "Class A warehouse space in Brasov &amp; Timisoara", ro: "Spațiu de depozitare Clasa A la Brașov &amp; Timișoara" },
  "stats.2": { en: "Offices across Romania", ro: "Birouri în toată România" },
  "stats.4": { en: "Non-stop warehouse security &amp; courier service", ro: "Securitate non-stop la depozite &amp; curierat" },
  "services.eyebrow": { en: "Services", ro: "Servicii" },
  "services.title": {
    en: "Everything your cargo needs, from pickup to delivery.",
    ro: "Tot ce are nevoie marfa ta, de la ridicare până la livrare.",
  },
  "svc1.title": { en: "Contract warehousing", ro: "Depozitare contractuală" },
  "svc1.text": {
    en: "Class A warehouses in Brasov (9,000 m²) and Timisoara (19,500 m²): inbound, storage, picking and shipping — managed in our WMS with real-time stock visibility and 24/7 security.",
    ro: "Depozite Clasa A la Brașov (9.000 m²) și Timișoara (19.500 m²): recepție, depozitare, picking și expediere — gestionate în WMS-ul nostru, cu vizibilitate în timp real a stocului și securitate 24/7.",
  },
  "svc2.title": { en: "Road transport", ro: "Transport rutier" },
  "svc2.text": {
    en: "FTL and LTL across Europe, from single urgent shipments to stable milk-run schedules. One contact, transparent offers, and the flexibility of a mid-size operator.",
    ro: "FTL și LTL în toată Europa, de la transporturi urgente singulare la programe stabile de tip milk-run. Un singur contact, oferte transparente și flexibilitatea unui operator de dimensiune medie.",
  },
  "svc3.title": { en: "Air &amp; ocean freight", ro: "Expediții aeriene &amp; maritime" },
  "svc3.text": {
    en: "As an IATA cargo agent we arrange air and sea forwarding for time-critical and intercontinental flows — customs handling included.",
    ro: "Ca agent cargo IATA, organizăm expediții aeriene și maritime pentru fluxuri critice ca timp și intercontinentale — inclusiv formalitățile vamale.",
  },
  "svc4.title": { en: "Tailored logistics concepts", ro: "Concepte logistice personalizate" },
  "svc4.text": {
    en: "Custom solutions that combine supply, storage and distribution in one flow — labelling, kitting and repacking, handled by trained, internally certified operators.",
    ro: "Soluții personalizate care combină aprovizionarea, depozitarea și distribuția într-un singur flux — etichetare, kitting și reambalare, realizate de operatori instruiți și certificați intern.",
  },
  "offices.eyebrow": { en: "Where we are", ro: "Unde ne găsești" },
  "offices.title": { en: "Five cities, one team you can actually reach.", ro: "Cinci orașe, o singură echipă pe care chiar o poți contacta." },
  "offices.md": { en: "Managing Director", ro: "Director General" },
  "tag.hq": { en: "HQ", ro: "Sediu central" },
  "tag.wh": { en: "Warehouse · 9,000 m²", ro: "Depozit · 9.000 m²" },
  "tag.wh2": { en: "Warehouse · 19,500 m²", ro: "Depozit · 19.500 m²" },
  "tag.office": { en: "Office", ro: "Birou" },
  "clients.eyebrow": { en: "Trusted by", ro: "Clienții noștri" },
  "clients.title": { en: "Manufacturers who can't afford a stopped line.", ro: "Producători care nu-și permit o linie oprită." },
  "contact.eyebrow": { en: "Contact", ro: "Contact" },
  "contact.title": {
    en: 'Have cargo that needs a&nbsp;home or a&nbsp;road? <em style="font-style:normal;color:#6FCFAC">Let\'s talk.</em>',
    ro: 'Ai marfă care are nevoie de un&nbsp;depozit sau de un&nbsp;drum? <em style="font-style:normal;color:#6FCFAC">Hai să vorbim.</em>',
  },
  "contact.md": { en: "— Managing Director", ro: "— Director General" },
  "form.name": { en: "Name", ro: "Nume" },
  "form.company": { en: "Company", ro: "Companie" },
  "form.email": { en: "Email", ro: "Email" },
  "form.phone": { en: "Phone", ro: "Telefon" },
  "form.service": { en: "What do you need?", ro: "Ce ai nevoie?" },
  "form.service.warehousing": { en: "Contract warehousing", ro: "Depozitare contractuală" },
  "form.service.road": { en: "Road transport", ro: "Transport rutier" },
  "form.service.airocean": { en: "Air & ocean freight", ro: "Expediții aeriene & maritime" },
  "form.service.other": { en: "Something else", ro: "Altceva" },
  "form.message": { en: "Message", ro: "Mesaj" },
  "form.submit": { en: "Send request", ro: "Trimite cererea" },
  "form.note": {
    en: "Opens your email app with this pre-filled, addressed to our team.",
    ro: "Se deschide aplicația ta de email cu mesajul completat, adresat echipei noastre.",
  },
  "cookie.text": {
    en: "We use your browser's local storage to remember your language choice. No tracking cookies.",
    ro: "Folosim stocarea locală a browserului ca să reținem limba aleasă. Fără cookie-uri de tracking.",
  },
  "cookie.accept": { en: "Got it", ro: "Am înțeles" },
  "fab.label": { en: "Quick contact", ro: "Contact rapid" },
  "notfound.eyebrow": { en: "404", ro: "404" },
  "notfound.title": { en: "This route never left the warehouse.", ro: "Ruta asta n-a plecat niciodată din depozit." },
  "notfound.text": { en: "The page you're looking for doesn't exist or has moved.", ro: "Pagina pe care o cauți nu există sau a fost mutată." },
  "notfound.cta": { en: "Back to homepage", ro: "Înapoi la pagina principală" },
  "svc1.bullet.1": { en: "Inbound, storage, picking and shipping", ro: "Recepție, depozitare, picking și expediere" },
  "svc1.bullet.2": { en: "Own WMS with real-time stock visibility", ro: "WMS propriu, cu vizibilitate a stocului în timp real" },
  "svc1.bullet.3": { en: "24/7 security at both warehouses", ro: "Securitate 24/7 la ambele depozite" },
  "svc1.bullet.4": { en: "Class A space: 9,000 m² in Brasov, 19,500 m² in Timisoara", ro: "Spațiu Clasa A: 9.000 m² la Brașov, 19.500 m² la Timișoara" },
  "svc2.bullet.1": { en: "FTL and LTL across Europe", ro: "FTL și LTL în toată Europa" },
  "svc2.bullet.2": { en: "Stable milk-run schedules or single urgent shipments", ro: "Rute milk-run stabile sau transporturi urgente singulare" },
  "svc2.bullet.3": { en: "Own fleet plus vetted partner carriers", ro: "Flotă proprie plus transportatori parteneri verificați" },
  "svc2.bullet.4": { en: "One point of contact, transparent pricing", ro: "Un singur punct de contact, oferte transparente" },
  "svc3.bullet.1": { en: "Certified IATA cargo agent", ro: "Agent cargo IATA certificat" },
  "svc3.bullet.2": { en: "Customs formalities handled end to end", ro: "Formalități vamale gestionate integral" },
  "svc3.bullet.3": { en: "Built for time-critical shipments", ro: "Construit pentru expediții critice ca timp" },
  "svc3.bullet.4": { en: "Intercontinental routes", ro: "Rute intercontinentale" },
  "svc4.bullet.1": { en: "Supply, storage and distribution in one flow", ro: "Aprovizionare, depozitare și distribuție într-un singur flux" },
  "svc4.bullet.2": { en: "Labelling, kitting and repacking", ro: "Etichetare, kitting și reambalare" },
  "svc4.bullet.3": { en: "Trained, internally certified operators", ro: "Operatori instruiți și certificați intern" },
  "svc4.bullet.4": { en: "Solutions adapted to your industry", ro: "Soluții adaptate pe industria ta" },
  "breadcrumb.home": { en: "Home", ro: "Acasă" },
  "breadcrumb.offices": { en: "Offices", ro: "Birouri" },
  "breadcrumb.services": { en: "Services", ro: "Servicii" },
  "office.team": { en: "Local team", ro: "Echipa locală" },
  "office.mapTitle": { en: "Map", ro: "Hartă" },
  "dept.management": { en: "Management", ro: "Management" },
  "dept.sales": { en: "Sales", ro: "Vânzări" },
  "dept.operational": { en: "Operational", ro: "Operațional" },
  "dept.warehouse": { en: "Warehouse", ro: "Depozit" },
  "dept.financial": { en: "Financial", ro: "Financiar" },
  "dept.sea & air": { en: "Sea & Air", ro: "Maritim & Aerian" },
  "process.eyebrow": { en: "How we work", ro: "Cum lucrăm" },
  "process.title": { en: "From pickup to delivery, in four steps.", ro: "De la ridicare la livrare, în patru pași." },
  "process.1.title": { en: "Pickup", ro: "Ridicare" },
  "process.1.text": { en: "We collect goods from your supplier or production line, anywhere in Europe.", ro: "Preluăm marfa de la furnizorul sau linia ta de producție, oriunde în Europa." },
  "process.2.title": { en: "Warehousing", ro: "Depozitare" },
  "process.2.text": { en: "Received, checked and stored in our Class A warehouses, visible in real time in our WMS.", ro: "Recepționată, verificată și depozitată în depozitele noastre Clasa A, vizibilă în timp real în WMS." },
  "process.3.title": { en: "Transport", ro: "Transport" },
  "process.3.text": { en: "FTL, LTL, air or ocean freight — whichever mode fits the deadline and the budget.", ro: "FTL, LTL, transport aerian sau maritim — orice mod de transport se potrivește termenului și bugetului." },
  "process.4.title": { en: "Delivery", ro: "Livrare" },
  "process.4.text": { en: "Delivered on schedule, with full tracking and a single point of contact throughout.", ro: "Livrată la termen, cu urmărire completă și un singur punct de contact pe tot parcursul." },
  "trust.eyebrow": { en: "Certified & compliant", ro: "Certificat & conform" },
  "trust.title": { en: "Standards you can verify, not just claim.", ro: "Standarde pe care le poți verifica, nu doar declara." },
  "trust.iso9001.text": { en: "Quality management system, audited annually.", ro: "Sistem de management al calității, auditat anual." },
  "trust.iso14001.text": { en: "Environmental management across all warehouses.", ro: "Management de mediu în toate depozitele." },
  "trust.iata.text": { en: "Certified to issue air waybills and handle air cargo.", ro: "Certificați pentru emiterea de scrisori de transport aerian și manipulare cargo aerian." },
  "testimonials.eyebrow": { en: "What clients say", ro: "Ce spun clienții" },
  "testimonials.title": { en: "Producers who can't afford to guess.", ro: "Producători care nu-și permit să ghicească." },
  "testimonials.1.quote": {
    en: "ITC picks up, stores and delivers exactly when they say they will. That predictability is worth more to us than a lower quote.",
    ro: "ITC preia, depozitează și livrează exact când spun că o vor face. Predictibilitatea asta valorează pentru noi mai mult decât o ofertă mai mică.",
  },
  "testimonials.1.role": { en: "Operations Director, tier-1 automotive supplier", ro: "Director Operațiuni, furnizor auto tier-1" },
  "testimonials.2.quote": {
    en: "We moved our Romanian distribution to ITC's Brasov warehouse two years ago. Stock visibility in their WMS ended most of our reconciliation calls.",
    ro: "Am mutat distribuția noastră din România la depozitul ITC din Brașov acum doi ani. Vizibilitatea stocului în WMS-ul lor a eliminat majoritatea apelurilor de reconciliere.",
  },
  "testimonials.2.role": { en: "Supply Chain Manager, home appliances manufacturer", ro: "Manager Lanț de Aprovizionare, producător de electrocasnice" },
  "testimonials.3.quote": {
    en: "Air freight through their IATA desk saved a production line for us once — customs cleared before the truck even reached the warehouse.",
    ro: "Cargo-ul aerian prin biroul lor IATA ne-a salvat o linie de producție odată — vama a fost gestionată înainte ca TIR-ul să ajungă la depozit.",
  },
  "testimonials.3.role": { en: "Plant Manager, industrial components producer", ro: "Director de Fabrică, producător de componente industriale" },
};
